#!/bin/sh

##############################################################
#           ____ _____ ____ _       ____  _______  ______    #
#          / __ ) ___// __ \ |     / /  |/  / __ \/ ____/    #
#         / __  \__ \/ /_/ / | /| / / /|_/ / /_/ / /         #
#     _  / /_/ /__/ / ____/| |/ |/ / /  / / _, _/ /___       #
#    (_)/_____/____/_/     |__/|__/_/  /_/_/ |_|\____/       #
#                                                            #
##############################################################

#                 __  __  _                 
#      ________  / /_/ /_(_)___  ____ ______
#     / ___/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    (__  )  __/ /_/ /_/ / / / / /_/ (__  ) 
#   /____/\___/\__/\__/_/_/ /_/\__, /____/  
#                             /____/        

bspc config border_width                1
bspc config window_gap                  7
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config pointer_modifier            mod1
bspc config pointer_action1             move
bspc config active_border_color "$(xrdb -query | awk '/color1/ {print $2}')"

#                  __             
#      _______  __/ /__  _____    
#     / ___/ / / / / _ \/ ___/    
#    / /  / /_/ / /  __(__  )     
#   /_/   \__,_/_/\___/____/      

bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^5'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a Pavucontrol desktop='^6'
bspc rule -a install4j-burp-StartBurp desktop='^7'

bspc rule -a Zathura state=tiled

#                             _ __                 
#      ____ ___  ____  ____  (_) /_____  __________
#     / __ `__ \/ __ \/ __ \/ / __/ __ \/ ___/ ___/
#    / / / / / / /_/ / / / / / /_/ /_/ / /  (__  ) 
#   /_/ /_/ /_/\____/_/ /_/_/\__/\____/_/  /____/  

tmp_file="$(mktemp)"
sh "$SCRIPT_DIR/bspwm_reorder_desktops.sh" -g "${tmp_file}"
monitors="$(xrandr -q | grep -w 'connected' | awk '{ print $1 }')"
if [ "$(echo "${monitors}" | wc -l)" -eq 2 ]; then
    # Internal and external monitor.
    ext_mon="$(echo "${monitors}" | grep -v LVDS)"
    int_mon="$(echo "${monitors}" | grep LVDS)"

    xrandr --output "${ext_mon}" --primary --auto\
        --output "${int_mon}" --auto --below "${ext_mon}"

    bspc monitor "${ext_mon}" -d 1 2 3 4
    bspc monitor "${int_mon}" -d 5 6 7

    EXTMONITOR="${ext_mon}" sh "${HOME}/.config/polybar/polybar.sh" \
        "top-internal" "top-external" "bottom-external"

    sh "$SCRIPT_DIR/bspwm_reorder_desktops.sh" -r "${tmp_file}"
else
    # Internal monitor only.
    int_mon="$(echo "${monitors}" | grep LVDS)"
    xrandr --output "${int_mon}" --auto
    for display in $(xrandr -q | grep -w 'disconnected' | awk '{print $1}'); do
        xrandr --output "${display}" --off
    done
    if [ "${int_mon}" = "LVDS-1" ]; then
        bspc monitor "${int_mon}" -d 1 2 3 4 5 6 7
        WIRELESS_INTERFACE='wlan0'\
            WIRED_INTERFACE='eth0'\
            MONITOR="${int_mon}"\
            sh "${HOME}/.config/polybar/polybar.sh" "top-internal"
        bspc config bottom_padding 0
    else
        bspc monitor "${int_mon}" -d 1 2 3 4 5 6 7
        sh "${HOME}/.config/polybar/polybar.sh" "top-internal"
        bspc config bottom_padding 0
    fi

    sh "$SCRIPT_DIR/bspwm_reorder_desktops.sh" -r "${tmp_file}"
fi

rm "${tmp_file}"

#             __             __            
#       _____/ /_____ ______/ /___  ______ 
#      / ___/ __/ __ `/ ___/ __/ / / / __ \
#     (__  ) /_/ /_/ / /  / /_/ /_/ / /_/ /
#    /____/\__/\__,_/_/   \__/\__,_/ .___/ 
#                                /_/      

# Java applications behave wierd without this.
export _JAVA_AWT_WM_NONREPARENTING=1

wal -R || wal --theme "$HOME/.config/wal/colorschemes/dark/gruvbox-tweaked.json"

# source the colors.
if [ -f "${HOME}/.cache/wal/colors.sh" ]; then
    # shellcheck source=/home/oliverwiegers/.cache/wal/colors.sh
    . "${HOME}/.cache/wal/colors.sh"
fi

# Launch needed software.
sxhkd &
unclutter -idle 2 &
xset r rate 280 40
setxkbmap us -variant intl
xmodmap ~/.Xmodmap
eval "$(ssh-agent)"
# shellcheck source=/home/oliverwiegers/.fehbg
. "${HOME}/.fehbg"
