#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux/screen.
if test "$SSH_AUTH_SOCK"; then
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi

# Taken from sshd(8) manpage.
if read -r proto cookie && [ -n "$DISPLAY" ]; then
    if [ "$(echo "$DISPLAY" | cut -c1-10)" = 'localhost' ]; then
        # X11UseLocalHost=yes
        echo add "unix:$(echo "$DISPLAY" |
            cut -c11-)" "$proto" "$cookie"
    else
        # X11UseLocalHost=no
        echo add "$DISPLAY" "$proto" "$cookie"
    fi | xauth -q -
fi
